config/routes.rb
Rails.application.routes.draw do
  get 'subparanoids/index'
  root "paranoiacs#index"
  resources :paranoiacs do
    resources :subparanoids
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/paranoiac.rb
class Paranoiac < ActiveRecord::Base
  acts_as_paranoid
  has_many :subparanoids, dependent: :destroy
end

app/models/subparanoid.rb
class Subparanoid < ApplicationRecord
  acts_as_paranoidx
  belongs_to :paranoiac
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/paranoiacs_controller.rb
class ParanoiacsController < ApplicationController
  before_action :set_paranoiac, only: %i[ show edit update destroy ]

  # GET /paranoiacs or /paranoiacs.json
  def index
    @paranoiacs = Paranoiac.all
  end

  # GET /paranoiacs/1 or /paranoiacs/1.json
  def show
  end

  # GET /paranoiacs/new
  def new
    @paranoiac = Paranoiac.new
  end

  # GET /paranoiacs/1/edit
  def edit
  end

  # POST /paranoiacs or /paranoiacs.json
  def create
    @paranoiac = Paranoiac.new(paranoiac_params)

    respond_to do |format|
      if @paranoiac.save
        format.html { redirect_to paranoiac_url(@paranoiac), notice: "Paranoiac was successfully created." }
        format.json { render :show, status: :created, location: @paranoiac }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @paranoiac.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paranoiacs/1 or /paranoiacs/1.json
  def update
    respond_to do |format|
      if @paranoiac.update(paranoiac_params)
        format.html { redirect_to paranoiac_url(@paranoiac), notice: "Paranoiac was successfully updated." }
        format.json { render :show, status: :ok, location: @paranoiac }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @paranoiac.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paranoiacs/1 or /paranoiacs/1.json
  def destroy
    @paranoiac.destroy

    respond_to do |format|
      format.html { redirect_to paranoiacs_url, notice: "Paranoiac was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paranoiac
      @paranoiac = Paranoiac.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def paranoiac_params
      params.require(:paranoiac).permit(:lastname, :firstname)
    end
end

app/controllers/subparanoids_controller.rb
class SubparanoidsController < ApplicationController
  before_action :set_subparanoids, only: %i[ show edit update destroy ]

  def index
    @subparanoids = Subparanoid.all
  end

  def show
  end

  def new
    @subparanoid = Subparanoid.new
  end

  def edit
  end

  def create
    @paranoiac = Paranoiac.find(params[:paranoiac_id])
    @subparanoid = @paranoiac.subparanoids.new(subparanoid_params)

    redirect_to paranoiac_path(@paranoiac)
  end

  def update
    respond_to do |format|
      if @subparanoid.update(subparanoid_params)
        format.html { redirect_to subparanoid_url(@subparanoid), notice: "subparanoid was successfully updated." }
        format.json { render :show, status: :ok, location: @subparanoid }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subparanoid.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @subparanoid.destroy

    respond_to do |format|
      format.html { redirect_to subparanoid_url, notice: "subparanoid was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_subparanoid
    @subparanoid = Subparanoid.find(params[:id])
  end

  def subparanoid_params
    params.require(:subparanoid).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paranoiacs_helper.rb
module ParanoiacsHelper
end

app/helpers/subparanoids_helper.rb
module SubparanoidsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paranoid</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/paranoiacs/_form.html.erb
<%= form_with(model: paranoiac) do |form| %>
  <% if paranoiac.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(paranoiac.errors.count, "error") %> prohibited this paranoiac from being saved:</h2>

      <ul>
        <% paranoiac.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :lastname, style: "display: block" %>
    <%= form.text_field :lastname %>
  </div>

  <div>
    <%= form.label :firstname, style: "display: block" %>
    <%= form.text_field :firstname %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/paranoiacs/_paranoiac.html.erb
<div id="<%= dom_id paranoiac %>">
  <p>
    <strong>Lastname:</strong>
    <%= paranoiac.lastname %>
  </p>

  <p>
    <strong>Firstname:</strong>
    <%= paranoiac.firstname %>
  </p>

</div>

app/views/paranoiacs/edit.html.erb
<h1>Editing paranoiac</h1>

<%= render "form", paranoiac: @paranoiac %>

<br>

<div>
  <%= link_to "Show this paranoiac", @paranoiac %> |
  <%= link_to "Back to paranoiacs", paranoiacs_path %>
</div>

app/views/paranoiacs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Paranoiacs</h1>

<div id="paranoiacs">
  <% @paranoiacs.each do |paranoiac| %>
    <%= render paranoiac %>
    <p>
      <%= link_to "Show this paranoiac", paranoiac %>
    </p>
  <% end %>
</div>

<%= link_to "New paranoiac", new_paranoiac_path %>

app/views/paranoiacs/new.html.erb
<h1>New paranoiac</h1>

<%= render "form", paranoiac: @paranoiac %>

<br>

<div>
  <%= link_to "Back to paranoiacs", paranoiacs_path %>
</div>

app/views/paranoiacs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @paranoiac %>

<div>
  <%= link_to "Edit this paranoiac", edit_paranoiac_path(@paranoiac) %> |
  <%= link_to "Back to paranoiacs", paranoiacs_path %>

  <%= button_to "Destroy this paranoiac", @paranoiac, method: :delete %>
</div>

app/views/subparanoids/index.html.erb
<h1>Subparanoids#index</h1>
<p>Find me in app/views/subparanoids/index.html.erb</p>